import { Letter } from '@/domain/enums.ts';

export const LETTER_DISTRIBUTION = {
  [Letter.A]: 10,
  [Letter.B]: 2,
  [Letter.C]: 2,
  [Letter.D]: 5,
  [Letter.E]: 12,
  [Letter.F]: 2,
  [Letter.G]: 3,
  [Letter.H]: 3,
  [Letter.I]: 9,
  [Letter.J]: 1,
  [Letter.K]: 1,
  [Letter.L]: 4,
  [Letter.M]: 2,
  [Letter.N]: 6,
  [Letter.O]: 7,
  [Letter.P]: 2,
  [Letter.Q]: 1,
  [Letter.R]: 6,
  [Letter.S]: 5,
  [Letter.T]: 7,
  [Letter.U]: 4,
  [Letter.V]: 2,
  [Letter.W]: 2,
  [Letter.X]: 1,
  [Letter.Y]: 2,
  [Letter.Z]: 1,
} as const;

export const LETTER_POINTS = {
  [Letter.A]: 1,
  [Letter.B]: 4,
  [Letter.C]: 4,
  [Letter.D]: 2,
  [Letter.E]: 1,
  [Letter.F]: 4,
  [Letter.G]: 3,
  [Letter.H]: 4,
  [Letter.I]: 1,
  [Letter.J]: 10,
  [Letter.K]: 5,
  [Letter.L]: 1,
  [Letter.M]: 3,
  [Letter.N]: 1,
  [Letter.O]: 1,
  [Letter.P]: 4,
  [Letter.Q]: 10,
  [Letter.R]: 1,
  [Letter.S]: 1,
  [Letter.T]: 1,
  [Letter.U]: 2,
  [Letter.V]: 4,
  [Letter.W]: 4,
  [Letter.X]: 8,
  [Letter.Y]: 4,
  [Letter.Z]: 10,
} as const;
